# Generated by Django 6.0 on 2026-01-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completes',
            new_name='is_completed',
        ),
    ]
