# Generated by Django 6.0 on 2026-01-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoss', '0002_rename_is_completes_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_ar',
            new_name='updated_at',
        ),
    ]
